[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildCommand = "git lfs install && git lfs pull"

[deploy]
startCommand = "/start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

